version: "3.3"
services:
  colas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    ports:
      - "8091:80"
    volumes:
      - .:/var/www/html
    # environment:
    #   - APP_ENV=local
    #   - APP_DEBUG=true
    #   - APP_KEY=base64:...
    #   - CACHE_DRIVER=redis
    #   - SESSION_DRIVER=redis
    #   - QUEUE_CONNECTION=redis
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis-server
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
